name: GitHub Readme YouTube Cards
on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCDg6VVhdeyN6vOjJTSSnS3g